on:
  push:
    branches:
      - main
    paths:
      - 'web-bff/**' # Trigger only for changes in the web-bff directory
  pull_request:
    branches:
      - main
      - '**' # Trigger for all PR branches
    paths:
      - 'web-bff/**' # Trigger only for changes in the web-bff directory

jobs:
  web-bff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/web-bff:latest -f web-bff/Dockerfile .
        working-directory: ../web-bff

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/web-bff:latest
